#!/bin/bash

# make a directory for sailor

mkdir sailor

# in aligned reads director, copy BAM files into sailor directory

cp *bam /N/slate/ewinlan/Class_Project/sailor

# merge adr-2 bam files

module load samtools

samtools merge output.bam input1.bam input2.bam

# in genome files directory, copy assembly genome file into sailor directory

 cp assembly.fasta /N/slate/ewinlan/Class_Project/sailor

# cp a bed file of known c. elegans SNPS into your own sailor directory from /N/project/HundleyLab/annotations

cp /N/project/HundleyLab/annotations/c.elegans.WS275.snps.nostrand.sorted.bed /N/slate/ewinlan/Class_Project/sailor

# also cp the sailor code into your working directory

cp -r /N/project/HundleyLab/FLARE/workflow_sailor /N/slate/ewinlan/Class_Project

# SAILOR is run by replacing variable names (file names, etc.) in a .json file that calls and runs the SAILOR script. We have the base .json, you just need to edit it to be specific for your analysis

nano cp_sailor.json

# paste this code and adjust it to your needs. This is what I did for this analysis:

 "samples_path":"/N/slate/ewinlan/Class_Project/sailor/",
  "samples": [
    "GSF4254-N2.merged.bam",  # List bam files here
  ],
  "reverse_stranded":true,  # This depends on your library prep and sequencing machine
  "reference_fasta": "/N/slate/ewinlan/Class_Project/genome_files/assembly.fasta",
  "known_snps": "/N/slate/ewinlan/Class_Project/sailor/c.elegans.WS275.snps.nostrand.sorted.bed",
  "edit_type": "AG",  # The type of edits you're looking for (A to I edits would be AG here)
  "output_dir": "/N/slate/ewinlan/Class_Project/sailor/outputs"
}

# now we are ready to run the snakefile
